import { inter, satoshi } from "@/constants/fonts";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
