import { inter, satoshi } from "@/constants/fonts";
import "./globals.css";
import Navbar from "@/common/layout/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${inter.className} bg-primary`}>
        <header
          className="sticky top-2 left-0 z-50 w-4/5 mx-auto p-4 flex items-center justify-between rounded-full"
          // style={{
          //   background: "rgba( 255, 255, 255, 0.2 )",
          //   backdropFilter: "blur( 8.5px )",
          // }}
        >
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
